max_iterations: 10
log_level: INFO

agents:
  delegator:
    type: DelegatorAgent
    llm:
      model_name: claude-3.5-sonnet
      api_key: ${ANTHROPIC_API_KEY}
      temperature: 0.7
      max_tokens: 4000
    max_retries: 3
    timeout: 300

  verifier:
    type: VerifierAgent
    llm:
      model_name: claude-3.5-sonnet
      api_key: ${ANTHROPIC_API_KEY}
      temperature: 0.2
      max_tokens: 2000
    max_retries: 3
    timeout: 300

  swe:
    type: SWEAgent
    llm:
      model_name: claude-3.5-sonnet
      api_key: ${ANTHROPIC_API_KEY}
      temperature: 0.7
      max_tokens: 8000
    max_retries: 3
    timeout: 600
